---
title: "Week 7 Assignment"
author: "Xhulia Turkaj"
date: "2023-10-28"
output: html_document
---

#WORKING WITH XML AND JSON IN R 


Pick three of your favorite books on one of your favorite subjects. At least one of the books should have more than one author. For each book, include the title, authors, and two or three other attributes that you find interesting.

Take the information that you’ve selected about these three books, and separately create three files which store the book’s information in HTML (using an html table), XML, and JSON formats (e.g. “books.html”, “books.xml”, and “books.json”). To help you better understand the different file structures, I’d prefer that you create each of these files “by hand” unless you’re already very comfortable with the file formats.

Write R code, using your packages of choice, to load the information from each of the three sources into separate R data frames. Are the three data frames identical?


```{r}
# Load libraries 
library(xml2)
library(data.table)
library(jsonlite)
```



Let's begin by first storing the information in an HTML table and save it as an HTML file

```{html}
#making sure to specify HTML as the language used for this code chunk. 

<html>
<head>
    <title>HTML Table Example</title>
</head>
<body>
    <table border="1">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Year of Publication</th>
                <th>Edition</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Data Science in Context: Foundations, Challenges, Opportunities</td>
                <td>Alfred Z. Spector <br>Peter Norvig <br> Chris Wiggins <br> Jeannette M. Wing</td> 
                <td>2022</td>
                <td>New</td>
            </tr>
            <tr>
                <td>Text Mining with R: A Tidy Approach </td>
                <td>Julia Silge  <br>David Robinson  </td>
                <td>2017</td>
                <td>1st</td>
            </tr>
            <tr>
                <td>SQL for Data Analysis: Advanced Techniques for Transforming Data into Insights </td>
                <td>Cathy Tanimura </td>
                <td>2021</td>
                <td>1st</td>
            </tr>
        </tbody>
    </table>
</body>
</html>




```
Next I am storing the information in an xml format


